services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: compagnon_api

    env_file:
      - .env

    expose:
      - "8000"

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      
    depends_on:
      dvc-init:
        condition: service_completed_successfully
      mlflow:
        condition: service_started

    restart: unless-stopped

  nginx:
    image: nginx:latest

    container_name: compagnon_nginx

    ports:
      - "8080:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/control:/usr/share/nginx/html/control:ro
      - ./nginx/auth:/etc/nginx/auth:ro

    depends_on:
      - api

    restart: unless-stopped
  
  dvc-init:
      build:
        context: .
        dockerfile: Dockerfile.dvc-runner

      working_dir: /workspace

      volumes:
        - .:/workspace
        - ${HOME}/.cache/pydrive2fs:/home/dvc/.cache/pydrive2fs
      environment:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}

      command:
        - sh
        - -c
        - |
          git config --global --add safe.directory /workspace
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          exec dvc pull

      restart: "no"

  dvc:
    build:
      context: .
      dockerfile: Dockerfile.dvc-runner
      args:
        DVC_UID: ${DVC_UID}
        DVC_GID: ${DVC_GID}

    container_name: compagnon_dvc

    user: "${DVC_UID}:${DVC_GID}"
    
    working_dir: /workspace

    volumes:
      - .:/workspace
      - ${HOME}/.cache/pydrive2fs:/home/dvc/.cache/pydrive2fs

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}

    depends_on:
      - mlflow

    command:
      - sh
      - -c
      - |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"
        exec sleep infinity
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.5.0

    container_name: compagnon_mlflow

    expose:
      - "5000"

    volumes:
      - ./mlflow:/mlflow

    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --allowed-hosts
      - "localhost:*,127.0.0.1:*,mlflow:5000"
      - --backend-store-uri
      - sqlite:////mlflow/mlflow.db
      - --artifacts-destination
      - /mlflow/artifacts

    restart: unless-stopped
    
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: compagnon_airflow

    user: "${AIRFLOW_UID}:0"
    
    group_add:
      - "${DOCKER_GID}"

    expose:
      - "8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/data/airflow.db"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: "/opt/airflow/data/simple_auth_manager_passwords.json"
      AIRFLOW__API__BASE_URL: http://localhost:8080/control/airflow
      AIRFLOW__WORKERS__EXECUTION_API_TIMEOUT: "30"
      AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL: "10"
      AIRFLOW__DAG_PROCESSOR__MIN_FILE_PROCESS_INTERVAL: "10"

    command: >
      bash -c "
      airflow db migrate &&
      airflow standalone
      "

    depends_on:
      - mlflow
      - dvc

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.14.0

    container_name: compagnon_prometheus

    expose:
      - "9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - --web.external-url=http://localhost:8080/control/prometheus
      - --web.route-prefix=/
    
    depends_on:
      - api

    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.2.0

    container_name: compagnon_grafana

    expose:
      - "3000"

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: http://localhost:8080/control/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

    depends_on:
      - prometheus

    restart: unless-stopped

  tests:
      build:
        context: .
        dockerfile: Dockerfile.test

      env_file:
        - .env

      volumes:
        - ./tests:/app/tests:ro
        - ./app:/app/app:ro
        - ./src:/app/src:ro

      profiles:
        - test

volumes:
  grafana_data:
  prometheus_data:

  