[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "compagnon-immobilier-mlops"
version = "0.1.0"
description = "Pipeline MLOps pour la prédiction du prix au m² immobilier"
requires-python = ">=3.12"

dependencies = [
    "pandas",
    "pyarrow",
    "requests",
    "scikit-learn",
    "pydantic",
    "fastapi",
    "python-dotenv",
    "uvicorn",
    "dvc[gdrive]",
]

[tool.setuptools.packages.find]
where = ["src"]