{
 "title": "Compagnon Immobilier - API Monitoring",
 "description": "Monitoring de l'api compagnon immobilier",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total predictions",
   "type": "timeseries",
   "description": "Montre le total des prédictions effectuées dans le temps",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "compagnon_predictions_total", "legendFormat": "{{Total Predictions}}" }
   ]
  },
  {
   "title": "Prediction rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(compagnon_predictions_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average prediction latency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(compagnon_prediction_duration_seconds_sum[5m])",
     "legendFormat": "__auto"
    },
    {},
    {
     "expr": "rate(compagnon_prediction_duration_seconds_sum[5m])\r\n/\r\nrate(compagnon_prediction_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions error",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "compagnon_prediction_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction latency p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(compagnon_prediction_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}