name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-24.04
    env:
      API_KEY: test_ci_key

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Création du fichier .env
        run: |
          cat <<EOF > .env
          API_KEY=${API_KEY}
          AIRFLOW_UID=1000
          DOCKER_GID=999
          EOF

      - name: Construction de l'image de tests
        run: |
          docker compose --profile test build tests

      - name: Exécution des tests
        run: |
          docker compose --profile test run --rm tests

      - name: Construction de l'image API
        run: |
          docker compose build api

      - name: Construction des images d'orchestration
        run: |
          docker compose build dvc airflow